# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscilla.ui'
#
# Created: Thu Nov 15 08:45:19 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OscillaWindow(object):
    def setupUi(self, OscillaWindow):
        OscillaWindow.setObjectName(_fromUtf8("OscillaWindow"))
        OscillaWindow.resize(892, 468)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("IcepapCfg Icons/gnome-monitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OscillaWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(OscillaWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hloAll = QtGui.QHBoxLayout()
        self.hloAll.setObjectName(_fromUtf8("hloAll"))
        self.vloControls = QtGui.QVBoxLayout()
        self.vloControls.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.vloControls.setObjectName(_fromUtf8("vloControls"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelDrivers = QtGui.QLabel(self.centralwidget)
        self.labelDrivers.setMaximumSize(QtCore.QSize(57, 16777215))
        self.labelDrivers.setObjectName(_fromUtf8("labelDrivers"))
        self.horizontalLayout_3.addWidget(self.labelDrivers)
        self.labelSignals = QtGui.QLabel(self.centralwidget)
        self.labelSignals.setMaximumSize(QtCore.QSize(137, 16777215))
        self.labelSignals.setObjectName(_fromUtf8("labelSignals"))
        self.horizontalLayout_3.addWidget(self.labelSignals)
        self.vloControls.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cbDrivers = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDrivers.sizePolicy().hasHeightForWidth())
        self.cbDrivers.setSizePolicy(sizePolicy)
        self.cbDrivers.setMaximumSize(QtCore.QSize(57, 16777215))
        self.cbDrivers.setObjectName(_fromUtf8("cbDrivers"))
        self.horizontalLayout_2.addWidget(self.cbDrivers)
        self.cbSignals = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSignals.sizePolicy().hasHeightForWidth())
        self.cbSignals.setSizePolicy(sizePolicy)
        self.cbSignals.setMaximumSize(QtCore.QSize(137, 16777215))
        self.cbSignals.setObjectName(_fromUtf8("cbSignals"))
        self.horizontalLayout_2.addWidget(self.cbSignals)
        self.vloControls.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.vloControls.addWidget(self.line)
        self.hloAxes = QtGui.QHBoxLayout()
        self.hloAxes.setObjectName(_fromUtf8("hloAxes"))
        self.labelAxis = QtGui.QLabel(self.centralwidget)
        self.labelAxis.setObjectName(_fromUtf8("labelAxis"))
        self.hloAxes.addWidget(self.labelAxis)
        self.rbAxis1 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis1.setObjectName(_fromUtf8("rbAxis1"))
        self.hloAxes.addWidget(self.rbAxis1)
        self.rbAxis2 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis2.setObjectName(_fromUtf8("rbAxis2"))
        self.hloAxes.addWidget(self.rbAxis2)
        self.rbAxis3 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis3.setObjectName(_fromUtf8("rbAxis3"))
        self.hloAxes.addWidget(self.rbAxis3)
        self.vloControls.addLayout(self.hloAxes)
        self.btnAdd = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.vloControls.addWidget(self.btnAdd)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelRemove = QtGui.QLabel(self.centralwidget)
        self.labelRemove.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labelRemove.setObjectName(_fromUtf8("labelRemove"))
        self.horizontalLayout.addWidget(self.labelRemove)
        self.btnRemoveSel = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveSel.sizePolicy().hasHeightForWidth())
        self.btnRemoveSel.setSizePolicy(sizePolicy)
        self.btnRemoveSel.setMaximumSize(QtCore.QSize(82, 16777215))
        self.btnRemoveSel.setObjectName(_fromUtf8("btnRemoveSel"))
        self.horizontalLayout.addWidget(self.btnRemoveSel)
        self.btnRemoveAll = QtGui.QPushButton(self.centralwidget)
        self.btnRemoveAll.setMaximumSize(QtCore.QSize(46, 16777215))
        self.btnRemoveAll.setObjectName(_fromUtf8("btnRemoveAll"))
        self.horizontalLayout.addWidget(self.btnRemoveAll)
        self.vloControls.addLayout(self.horizontalLayout)
        self.lvActiveSig = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvActiveSig.sizePolicy().hasHeightForWidth())
        self.lvActiveSig.setSizePolicy(sizePolicy)
        self.lvActiveSig.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lvActiveSig.setObjectName(_fromUtf8("lvActiveSig"))
        self.vloControls.addWidget(self.lvActiveSig)
        self.btnShift = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnShift.setObjectName(_fromUtf8("btnShift"))
        self.vloControls.addWidget(self.btnShift)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vloControls.addItem(spacerItem)
        self.btnCLoop = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCLoop.sizePolicy().hasHeightForWidth())
        self.btnCLoop.setSizePolicy(sizePolicy)
        self.btnCLoop.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCLoop.setPalette(palette)
        self.btnCLoop.setObjectName(_fromUtf8("btnCLoop"))
        self.vloControls.addWidget(self.btnCLoop)
        self.btnCurrents = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCurrents.sizePolicy().hasHeightForWidth())
        self.btnCurrents.setSizePolicy(sizePolicy)
        self.btnCurrents.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCurrents.setPalette(palette)
        self.btnCurrents.setObjectName(_fromUtf8("btnCurrents"))
        self.vloControls.addWidget(self.btnCurrents)
        self.btnTarget = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTarget.sizePolicy().hasHeightForWidth())
        self.btnTarget.setSizePolicy(sizePolicy)
        self.btnTarget.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnTarget.setPalette(palette)
        self.btnTarget.setObjectName(_fromUtf8("btnTarget"))
        self.vloControls.addWidget(self.btnTarget)
        self.hloAll.addLayout(self.vloControls)
        self.vloCurves = QtGui.QVBoxLayout()
        self.vloCurves.setObjectName(_fromUtf8("vloCurves"))
        self.hloCurveButtons = QtGui.QHBoxLayout()
        self.hloCurveButtons.setObjectName(_fromUtf8("hloCurveButtons"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem1)
        self.btnSeeAll = QtGui.QPushButton(self.centralwidget)
        self.btnSeeAll.setObjectName(_fromUtf8("btnSeeAll"))
        self.hloCurveButtons.addWidget(self.btnSeeAll)
        self.btnPause = QtGui.QPushButton(self.centralwidget)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.hloCurveButtons.addWidget(self.btnPause)
        self.btnResetY = QtGui.QPushButton(self.centralwidget)
        self.btnResetY.setObjectName(_fromUtf8("btnResetY"))
        self.hloCurveButtons.addWidget(self.btnResetY)
        self.btnResetX = QtGui.QPushButton(self.centralwidget)
        self.btnResetX.setObjectName(_fromUtf8("btnResetX"))
        self.hloCurveButtons.addWidget(self.btnResetX)
        self.btnNow = QtGui.QPushButton(self.centralwidget)
        self.btnNow.setObjectName(_fromUtf8("btnNow"))
        self.hloCurveButtons.addWidget(self.btnNow)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem2)
        self.vloCurves.addLayout(self.hloCurveButtons)
        self.hloAll.addLayout(self.vloCurves)
        self.gridLayout.addLayout(self.hloAll, 0, 0, 1, 1)
        OscillaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OscillaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSignal_Sets = QtGui.QMenu(self.menubar)
        self.menuSignal_Sets.setObjectName(_fromUtf8("menuSignal_Sets"))
        OscillaWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OscillaWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OscillaWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(OscillaWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSettings = QtGui.QAction(OscillaWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionClosed_Loop = QtGui.QAction(OscillaWindow)
        self.actionClosed_Loop.setObjectName(_fromUtf8("actionClosed_Loop"))
        self.actionCurrents = QtGui.QAction(OscillaWindow)
        self.actionCurrents.setObjectName(_fromUtf8("actionCurrents"))
        self.actionTarget = QtGui.QAction(OscillaWindow)
        self.actionTarget.setObjectName(_fromUtf8("actionTarget"))
        self.actionAdd_Signals = QtGui.QAction(OscillaWindow)
        self.actionAdd_Signals.setObjectName(_fromUtf8("actionAdd_Signals"))
        self.menuFile.addAction(self.actionAdd_Signals)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuSignal_Sets.addAction(self.actionClosed_Loop)
        self.menuSignal_Sets.addAction(self.actionCurrents)
        self.menuSignal_Sets.addAction(self.actionTarget)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSignal_Sets.menuAction())

        self.retranslateUi(OscillaWindow)
        QtCore.QMetaObject.connectSlotsByName(OscillaWindow)

    def retranslateUi(self, OscillaWindow):
        OscillaWindow.setWindowTitle(_translate("OscillaWindow", "Dummy Window Title", None))
        self.labelDrivers.setText(_translate("OscillaWindow", "Driver:", None))
        self.labelSignals.setText(_translate("OscillaWindow", "Signal:", None))
        self.labelAxis.setText(_translate("OscillaWindow", "Y-axis:", None))
        self.rbAxis1.setText(_translate("OscillaWindow", "1", None))
        self.rbAxis2.setText(_translate("OscillaWindow", "2", None))
        self.rbAxis3.setText(_translate("OscillaWindow", "3", None))
        self.btnAdd.setText(_translate("OscillaWindow", "Add Signal", None))
        self.labelRemove.setText(_translate("OscillaWindow", "Remove:", None))
        self.btnRemoveSel.setText(_translate("OscillaWindow", "Selected", None))
        self.btnRemoveAll.setText(_translate("OscillaWindow", "All", None))
        self.btnShift.setText(_translate("OscillaWindow", "Shift Y-axis", None))
        self.btnCLoop.setText(_translate("OscillaWindow", "* Closed Loop *", None))
        self.btnCurrents.setText(_translate("OscillaWindow", "* Currents *", None))
        self.btnTarget.setText(_translate("OscillaWindow", "* Target *", None))
        self.btnSeeAll.setText(_translate("OscillaWindow", "All Data", None))
        self.btnSeeAll.setShortcut(_translate("OscillaWindow", "Ctrl+S", None))
        self.btnPause.setText(_translate("OscillaWindow", "Pause", None))
        self.btnResetY.setText(_translate("OscillaWindow", "Reset Y", None))
        self.btnResetX.setText(_translate("OscillaWindow", "Reset X", None))
        self.btnNow.setText(_translate("OscillaWindow", "Now", None))
        self.menuFile.setTitle(_translate("OscillaWindow", "File", None))
        self.menuSignal_Sets.setTitle(_translate("OscillaWindow", "Signal Sets", None))
        self.actionExit.setText(_translate("OscillaWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("OscillaWindow", "Ctrl+X", None))
        self.actionSettings.setText(_translate("OscillaWindow", "Settings", None))
        self.actionClosed_Loop.setText(_translate("OscillaWindow", "Closed Loop", None))
        self.actionCurrents.setText(_translate("OscillaWindow", "Currents", None))
        self.actionTarget.setText(_translate("OscillaWindow", "Target", None))
        self.actionAdd_Signals.setText(_translate("OscillaWindow", "Add Signals", None))
        self.actionAdd_Signals.setShortcut(_translate("OscillaWindow", "Ctrl+A", None))

