# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(954, 814)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../../.designer/backup/IcepapCfg Icons/gnome-monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WindowMain.setWindowIcon(icon)
        WindowMain.setStyleSheet("font: 9pt;")
        self.centralwidget = QtWidgets.QWidget(WindowMain)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(155, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelDrivers = QtWidgets.QLabel(self.widget_2)
        self.labelDrivers.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelDrivers.setObjectName("labelDrivers")
        self.gridLayout_4.addWidget(self.labelDrivers, 0, 0, 1, 1)
        self.labelSignals = QtWidgets.QLabel(self.widget_2)
        self.labelSignals.setMaximumSize(QtCore.QSize(40, 16777215))
        self.labelSignals.setObjectName("labelSignals")
        self.gridLayout_4.addWidget(self.labelSignals, 0, 1, 1, 1)
        self.cbDrivers = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDrivers.sizePolicy().hasHeightForWidth())
        self.cbDrivers.setSizePolicy(sizePolicy)
        self.cbDrivers.setMinimumSize(QtCore.QSize(45, 0))
        self.cbDrivers.setMaximumSize(QtCore.QSize(35, 22))
        self.cbDrivers.setObjectName("cbDrivers")
        self.gridLayout_4.addWidget(self.cbDrivers, 1, 0, 1, 1)
        self.cbSignals = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSignals.sizePolicy().hasHeightForWidth())
        self.cbSignals.setSizePolicy(sizePolicy)
        self.cbSignals.setMinimumSize(QtCore.QSize(90, 0))
        self.cbSignals.setMaximumSize(QtCore.QSize(1000, 22))
        self.cbSignals.setObjectName("cbSignals")
        self.gridLayout_4.addWidget(self.cbSignals, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.line = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.hloAxes = QtWidgets.QHBoxLayout()
        self.hloAxes.setObjectName("hloAxes")
        self.labelAxis = QtWidgets.QLabel(self.widget_2)
        self.labelAxis.setMaximumSize(QtCore.QSize(35, 22))
        self.labelAxis.setObjectName("labelAxis")
        self.hloAxes.addWidget(self.labelAxis)
        self.sbAxis = QtWidgets.QSpinBox(self.widget_2)
        self.sbAxis.setMaximumSize(QtCore.QSize(50, 22))
        self.sbAxis.setMinimum(1)
        self.sbAxis.setMaximum(3)
        self.sbAxis.setObjectName("sbAxis")
        self.hloAxes.addWidget(self.sbAxis)
        self.verticalLayout.addLayout(self.hloAxes)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.red_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_radio.sizePolicy().hasHeightForWidth())
        self.red_radio.setSizePolicy(sizePolicy)
        self.red_radio.setStyleSheet("color: rgb(255, 0, 0);")
        self.red_radio.setObjectName("red_radio")
        self.color_radio_group = QtWidgets.QButtonGroup(WindowMain)
        self.color_radio_group.setObjectName("color_radio_group")
        self.color_radio_group.addButton(self.red_radio)
        self.gridLayout_7.addWidget(self.red_radio, 0, 0, 1, 1)
        self.green_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.green_radio.sizePolicy().hasHeightForWidth())
        self.green_radio.setSizePolicy(sizePolicy)
        self.green_radio.setStyleSheet("color: rgb(0, 255, 0);")
        self.green_radio.setObjectName("green_radio")
        self.color_radio_group.addButton(self.green_radio)
        self.gridLayout_7.addWidget(self.green_radio, 0, 1, 1, 1)
        self.blue_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_radio.sizePolicy().hasHeightForWidth())
        self.blue_radio.setSizePolicy(sizePolicy)
        self.blue_radio.setStyleSheet("color: rgb(0, 127, 255);")
        self.blue_radio.setObjectName("blue_radio")
        self.color_radio_group.addButton(self.blue_radio)
        self.gridLayout_7.addWidget(self.blue_radio, 0, 2, 1, 1)
        self.cyan_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyan_radio.sizePolicy().hasHeightForWidth())
        self.cyan_radio.setSizePolicy(sizePolicy)
        self.cyan_radio.setStyleSheet("color: rgb(0, 255, 255);")
        self.cyan_radio.setObjectName("cyan_radio")
        self.color_radio_group.addButton(self.cyan_radio)
        self.gridLayout_7.addWidget(self.cyan_radio, 0, 3, 1, 1)
        self.magenta_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magenta_radio.sizePolicy().hasHeightForWidth())
        self.magenta_radio.setSizePolicy(sizePolicy)
        self.magenta_radio.setStyleSheet("color: rgb(255, 192, 203);")
        self.magenta_radio.setObjectName("magenta_radio")
        self.color_radio_group.addButton(self.magenta_radio)
        self.gridLayout_7.addWidget(self.magenta_radio, 0, 4, 1, 1)
        self.yellow_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellow_radio.sizePolicy().hasHeightForWidth())
        self.yellow_radio.setSizePolicy(sizePolicy)
        self.yellow_radio.setStyleSheet("color: rgb(255, 255, 0);")
        self.yellow_radio.setObjectName("yellow_radio")
        self.color_radio_group.addButton(self.yellow_radio)
        self.gridLayout_7.addWidget(self.yellow_radio, 0, 5, 1, 1)
        self.darkred_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.darkred_radio.sizePolicy().hasHeightForWidth())
        self.darkred_radio.setSizePolicy(sizePolicy)
        self.darkred_radio.setStyleSheet("color: rgb(128, 0, 0);")
        self.darkred_radio.setObjectName("darkred_radio")
        self.color_radio_group.addButton(self.darkred_radio)
        self.gridLayout_7.addWidget(self.darkred_radio, 1, 0, 1, 1)
        self.darkgreen_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.darkgreen_radio.sizePolicy().hasHeightForWidth())
        self.darkgreen_radio.setSizePolicy(sizePolicy)
        self.darkgreen_radio.setStyleSheet("color: rgb(0, 128, 0);")
        self.darkgreen_radio.setObjectName("darkgreen_radio")
        self.color_radio_group.addButton(self.darkgreen_radio)
        self.gridLayout_7.addWidget(self.darkgreen_radio, 1, 1, 1, 1)
        self.darkblue_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.darkblue_radio.sizePolicy().hasHeightForWidth())
        self.darkblue_radio.setSizePolicy(sizePolicy)
        self.darkblue_radio.setStyleSheet("color: rgb(0, 0, 255);")
        self.darkblue_radio.setObjectName("darkblue_radio")
        self.color_radio_group.addButton(self.darkblue_radio)
        self.gridLayout_7.addWidget(self.darkblue_radio, 1, 2, 1, 1)
        self.dark_cyan_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_cyan_radio.sizePolicy().hasHeightForWidth())
        self.dark_cyan_radio.setSizePolicy(sizePolicy)
        self.dark_cyan_radio.setStyleSheet("color: rgb(0, 127, 127);")
        self.dark_cyan_radio.setObjectName("dark_cyan_radio")
        self.color_radio_group.addButton(self.dark_cyan_radio)
        self.gridLayout_7.addWidget(self.dark_cyan_radio, 1, 3, 1, 1)
        self.dark_magenta_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_magenta_radio.sizePolicy().hasHeightForWidth())
        self.dark_magenta_radio.setSizePolicy(sizePolicy)
        self.dark_magenta_radio.setStyleSheet("color: rgb(127, 0, 127);")
        self.dark_magenta_radio.setObjectName("dark_magenta_radio")
        self.color_radio_group.addButton(self.dark_magenta_radio)
        self.gridLayout_7.addWidget(self.dark_magenta_radio, 1, 4, 1, 1)
        self.dark_yellow_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_yellow_radio.sizePolicy().hasHeightForWidth())
        self.dark_yellow_radio.setSizePolicy(sizePolicy)
        self.dark_yellow_radio.setStyleSheet("color: rgb(127, 127, 0);")
        self.dark_yellow_radio.setObjectName("dark_yellow_radio")
        self.color_radio_group.addButton(self.dark_yellow_radio)
        self.gridLayout_7.addWidget(self.dark_yellow_radio, 1, 5, 1, 1)
        self.solidline_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solidline_radio.sizePolicy().hasHeightForWidth())
        self.solidline_radio.setSizePolicy(sizePolicy)
        self.solidline_radio.setStyleSheet("color: rgb(255, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/solidline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.solidline_radio.setIcon(icon1)
        self.solidline_radio.setObjectName("solidline_radio")
        self.linestyle_radio_group = QtWidgets.QButtonGroup(WindowMain)
        self.linestyle_radio_group.setObjectName("linestyle_radio_group")
        self.linestyle_radio_group.addButton(self.solidline_radio)
        self.gridLayout_7.addWidget(self.solidline_radio, 2, 0, 1, 1)
        self.dottedline_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dottedline_radio.sizePolicy().hasHeightForWidth())
        self.dottedline_radio.setSizePolicy(sizePolicy)
        self.dottedline_radio.setStyleSheet("color: rgb(255, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/dottedline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dottedline_radio.setIcon(icon2)
        self.dottedline_radio.setObjectName("dottedline_radio")
        self.linestyle_radio_group.addButton(self.dottedline_radio)
        self.gridLayout_7.addWidget(self.dottedline_radio, 2, 1, 1, 1)
        self.nomarker_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nomarker_radio.sizePolicy().hasHeightForWidth())
        self.nomarker_radio.setSizePolicy(sizePolicy)
        self.nomarker_radio.setStyleSheet("color: rgb(255, 0, 0);")
        self.nomarker_radio.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nomarker_radio.setIcon(icon3)
        self.nomarker_radio.setObjectName("nomarker_radio")
        self.marker_radio_group = QtWidgets.QButtonGroup(WindowMain)
        self.marker_radio_group.setObjectName("marker_radio_group")
        self.marker_radio_group.addButton(self.nomarker_radio)
        self.gridLayout_7.addWidget(self.nomarker_radio, 2, 2, 1, 1)
        self.circlemarker_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circlemarker_radio.sizePolicy().hasHeightForWidth())
        self.circlemarker_radio.setSizePolicy(sizePolicy)
        self.circlemarker_radio.setStyleSheet("color: rgb(255, 0, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circlemarker_radio.setIcon(icon4)
        self.circlemarker_radio.setObjectName("circlemarker_radio")
        self.marker_radio_group.addButton(self.circlemarker_radio)
        self.gridLayout_7.addWidget(self.circlemarker_radio, 2, 3, 1, 1)
        self.squaremarker_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.squaremarker_radio.sizePolicy().hasHeightForWidth())
        self.squaremarker_radio.setSizePolicy(sizePolicy)
        self.squaremarker_radio.setStyleSheet("color: rgb(255, 0, 0);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.squaremarker_radio.setIcon(icon5)
        self.squaremarker_radio.setObjectName("squaremarker_radio")
        self.marker_radio_group.addButton(self.squaremarker_radio)
        self.gridLayout_7.addWidget(self.squaremarker_radio, 2, 4, 1, 1)
        self.crossmarker_radio = Square_RadioBtn(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossmarker_radio.sizePolicy().hasHeightForWidth())
        self.crossmarker_radio.setSizePolicy(sizePolicy)
        self.crossmarker_radio.setStyleSheet("color: rgb(255, 0, 0);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crossmarker_radio.setIcon(icon6)
        self.crossmarker_radio.setObjectName("crossmarker_radio")
        self.marker_radio_group.addButton(self.crossmarker_radio)
        self.gridLayout_7.addWidget(self.crossmarker_radio, 2, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.btnAdd = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMaximumSize(QtCore.QSize(1000, 22))
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelRemove = QtWidgets.QLabel(self.widget_2)
        self.labelRemove.setMaximumSize(QtCore.QSize(50, 22))
        self.labelRemove.setObjectName("labelRemove")
        self.horizontalLayout.addWidget(self.labelRemove)
        self.btnRemoveSel = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveSel.sizePolicy().hasHeightForWidth())
        self.btnRemoveSel.setSizePolicy(sizePolicy)
        self.btnRemoveSel.setMaximumSize(QtCore.QSize(60, 22))
        self.btnRemoveSel.setObjectName("btnRemoveSel")
        self.horizontalLayout.addWidget(self.btnRemoveSel)
        self.btnRemoveAll = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveAll.sizePolicy().hasHeightForWidth())
        self.btnRemoveAll.setSizePolicy(sizePolicy)
        self.btnRemoveAll.setMaximumSize(QtCore.QSize(25, 22))
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.horizontalLayout.addWidget(self.btnRemoveAll)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lvActiveSig = QtWidgets.QListWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvActiveSig.sizePolicy().hasHeightForWidth())
        self.lvActiveSig.setSizePolicy(sizePolicy)
        self.lvActiveSig.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.lvActiveSig.setObjectName("lvActiveSig")
        self.verticalLayout.addWidget(self.lvActiveSig)
        self.btnShift = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMaximumSize(QtCore.QSize(1000, 22))
        self.btnShift.setObjectName("btnShift")
        self.verticalLayout.addWidget(self.btnShift)
        spacerItem = QtWidgets.QSpacerItem(128, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnCLoop = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCLoop.sizePolicy().hasHeightForWidth())
        self.btnCLoop.setSizePolicy(sizePolicy)
        self.btnCLoop.setMaximumSize(QtCore.QSize(1000, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCLoop.setPalette(palette)
        self.btnCLoop.setObjectName("btnCLoop")
        self.verticalLayout.addWidget(self.btnCLoop)
        self.btnCurrents = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCurrents.sizePolicy().hasHeightForWidth())
        self.btnCurrents.setSizePolicy(sizePolicy)
        self.btnCurrents.setMaximumSize(QtCore.QSize(1000, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCurrents.setPalette(palette)
        self.btnCurrents.setObjectName("btnCurrents")
        self.verticalLayout.addWidget(self.btnCurrents)
        self.btnTarget = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTarget.sizePolicy().hasHeightForWidth())
        self.btnTarget.setSizePolicy(sizePolicy)
        self.btnTarget.setMaximumSize(QtCore.QSize(1000, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnTarget.setPalette(palette)
        self.btnTarget.setObjectName("btnTarget")
        self.verticalLayout.addWidget(self.btnTarget)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.vloCurves = QtWidgets.QVBoxLayout()
        self.vloCurves.setObjectName("vloCurves")
        self.horizontalLayout_2.addLayout(self.vloCurves)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.hlo_enc2mot = QtWidgets.QHBoxLayout()
        self.hlo_enc2mot.setSpacing(2)
        self.hlo_enc2mot.setObjectName("hlo_enc2mot")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chkEctsTurn = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEctsTurn.sizePolicy().hasHeightForWidth())
        self.chkEctsTurn.setSizePolicy(sizePolicy)
        self.chkEctsTurn.setMinimumSize(QtCore.QSize(70, 0))
        self.chkEctsTurn.setMaximumSize(QtCore.QSize(80, 16))
        self.chkEctsTurn.setObjectName("chkEctsTurn")
        self.gridLayout_3.addWidget(self.chkEctsTurn, 0, 0, 1, 1)
        self.cb_enc_sel = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_enc_sel.sizePolicy().hasHeightForWidth())
        self.cb_enc_sel.setSizePolicy(sizePolicy)
        self.cb_enc_sel.setMinimumSize(QtCore.QSize(70, 16))
        self.cb_enc_sel.setMaximumSize(QtCore.QSize(150, 22))
        self.cb_enc_sel.setObjectName("cb_enc_sel")
        self.cb_enc_sel.addItem("")
        self.cb_enc_sel.addItem("")
        self.gridLayout_3.addWidget(self.cb_enc_sel, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 16))
        self.label.setMaximumSize(QtCore.QSize(70, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.txtEctsTurn = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEctsTurn.sizePolicy().hasHeightForWidth())
        self.txtEctsTurn.setSizePolicy(sizePolicy)
        self.txtEctsTurn.setMinimumSize(QtCore.QSize(80, 0))
        self.txtEctsTurn.setMaximumSize(QtCore.QSize(100, 18))
        self.txtEctsTurn.setReadOnly(True)
        self.txtEctsTurn.setObjectName("txtEctsTurn")
        self.gridLayout_3.addWidget(self.txtEctsTurn, 1, 1, 1, 1)
        self.hlo_enc2mot.addLayout(self.gridLayout_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hlo_enc2mot.addWidget(self.line_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setMinimumSize(QtCore.QSize(50, 0))
        self.btnClear.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_5.addWidget(self.btnClear, 0, 0, 1, 1)
        self.btnSeeAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeeAll.setMinimumSize(QtCore.QSize(50, 0))
        self.btnSeeAll.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSeeAll.setObjectName("btnSeeAll")
        self.gridLayout_5.addWidget(self.btnSeeAll, 0, 1, 1, 1)
        self.btnPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPause.setMinimumSize(QtCore.QSize(50, 0))
        self.btnPause.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPause.setObjectName("btnPause")
        self.gridLayout_5.addWidget(self.btnPause, 0, 2, 1, 1)
        self.btnResetY = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetY.setMinimumSize(QtCore.QSize(50, 0))
        self.btnResetY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnResetY.setObjectName("btnResetY")
        self.gridLayout_5.addWidget(self.btnResetY, 1, 0, 1, 1)
        self.btnResetX = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetX.setMinimumSize(QtCore.QSize(50, 0))
        self.btnResetX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnResetX.setObjectName("btnResetX")
        self.gridLayout_5.addWidget(self.btnResetX, 1, 1, 1, 1)
        self.btnNow = QtWidgets.QPushButton(self.centralwidget)
        self.btnNow.setMinimumSize(QtCore.QSize(50, 0))
        self.btnNow.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnNow.setObjectName("btnNow")
        self.gridLayout_5.addWidget(self.btnNow, 1, 2, 1, 1)
        self.hlo_enc2mot.addLayout(self.gridLayout_5)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.hlo_enc2mot.addWidget(self.line_7)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnSTATUS = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSTATUS.sizePolicy().hasHeightForWidth())
        self.btnSTATUS.setSizePolicy(sizePolicy)
        self.btnSTATUS.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSTATUS.setObjectName("btnSTATUS")
        self.gridLayout_6.addWidget(self.btnSTATUS, 0, 0, 1, 1)
        self.btnESYNC = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnESYNC.sizePolicy().hasHeightForWidth())
        self.btnESYNC.setSizePolicy(sizePolicy)
        self.btnESYNC.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnESYNC.setObjectName("btnESYNC")
        self.gridLayout_6.addWidget(self.btnESYNC, 1, 0, 1, 1)
        self.hlo_enc2mot.addLayout(self.gridLayout_6)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.hlo_enc2mot.addWidget(self.line_8)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnAxisOffsIncrease = QtWidgets.QToolButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisOffsIncrease.sizePolicy().hasHeightForWidth())
        self.btnAxisOffsIncrease.setSizePolicy(sizePolicy)
        self.btnAxisOffsIncrease.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAxisOffsIncrease.setMaximumSize(QtCore.QSize(50, 20))
        self.btnAxisOffsIncrease.setArrowType(QtCore.Qt.UpArrow)
        self.btnAxisOffsIncrease.setObjectName("btnAxisOffsIncrease")
        self.horizontalLayout_8.addWidget(self.btnAxisOffsIncrease)
        self.gridLayout_2.addWidget(self.widget_3, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnAxisScaleIncrease = QtWidgets.QToolButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisScaleIncrease.sizePolicy().hasHeightForWidth())
        self.btnAxisScaleIncrease.setSizePolicy(sizePolicy)
        self.btnAxisScaleIncrease.setMaximumSize(QtCore.QSize(50, 20))
        self.btnAxisScaleIncrease.setArrowType(QtCore.Qt.UpArrow)
        self.btnAxisScaleIncrease.setObjectName("btnAxisScaleIncrease")
        self.horizontalLayout_9.addWidget(self.btnAxisScaleIncrease)
        self.gridLayout_2.addWidget(self.widget_4, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(36, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(36, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnAxisOffsDecrease = QtWidgets.QToolButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisOffsDecrease.sizePolicy().hasHeightForWidth())
        self.btnAxisOffsDecrease.setSizePolicy(sizePolicy)
        self.btnAxisOffsDecrease.setMaximumSize(QtCore.QSize(50, 20))
        self.btnAxisOffsDecrease.setArrowType(QtCore.Qt.DownArrow)
        self.btnAxisOffsDecrease.setObjectName("btnAxisOffsDecrease")
        self.horizontalLayout_10.addWidget(self.btnAxisOffsDecrease)
        self.gridLayout_2.addWidget(self.widget_5, 2, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnAxisScaleDecrease = QtWidgets.QToolButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisScaleDecrease.sizePolicy().hasHeightForWidth())
        self.btnAxisScaleDecrease.setSizePolicy(sizePolicy)
        self.btnAxisScaleDecrease.setMaximumSize(QtCore.QSize(50, 20))
        self.btnAxisScaleDecrease.setArrowType(QtCore.Qt.DownArrow)
        self.btnAxisScaleDecrease.setObjectName("btnAxisScaleDecrease")
        self.horizontalLayout_11.addWidget(self.btnAxisScaleDecrease)
        self.gridLayout_2.addWidget(self.widget_6, 2, 2, 1, 1)
        self.btnAxisScaleAuto = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxisScaleAuto.sizePolicy().hasHeightForWidth())
        self.btnAxisScaleAuto.setSizePolicy(sizePolicy)
        self.btnAxisScaleAuto.setMaximumSize(QtCore.QSize(50, 20))
        self.btnAxisScaleAuto.setObjectName("btnAxisScaleAuto")
        self.gridLayout_2.addWidget(self.btnAxisScaleAuto, 2, 0, 1, 1)
        self.cbAxisCtrlSelect = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAxisCtrlSelect.sizePolicy().hasHeightForWidth())
        self.cbAxisCtrlSelect.setSizePolicy(sizePolicy)
        self.cbAxisCtrlSelect.setMaximumSize(QtCore.QSize(50, 20))
        self.cbAxisCtrlSelect.setObjectName("cbAxisCtrlSelect")
        self.cbAxisCtrlSelect.addItem("")
        self.cbAxisCtrlSelect.addItem("")
        self.cbAxisCtrlSelect.addItem("")
        self.cbAxisCtrlSelect.addItem("")
        self.gridLayout_2.addWidget(self.cbAxisCtrlSelect, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(50, 22))
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.hlo_enc2mot.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hlo_enc2mot.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnWhitebg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWhitebg.sizePolicy().hasHeightForWidth())
        self.btnWhitebg.setSizePolicy(sizePolicy)
        self.btnWhitebg.setMinimumSize(QtCore.QSize(20, 20))
        self.btnWhitebg.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/whitebg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWhitebg.setIcon(icon7)
        self.btnWhitebg.setIconSize(QtCore.QSize(18, 18))
        self.btnWhitebg.setObjectName("btnWhitebg")
        self.verticalLayout_3.addWidget(self.btnWhitebg)
        self.btnGreybg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGreybg.sizePolicy().hasHeightForWidth())
        self.btnGreybg.setSizePolicy(sizePolicy)
        self.btnGreybg.setMinimumSize(QtCore.QSize(20, 20))
        self.btnGreybg.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/greybg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGreybg.setIcon(icon8)
        self.btnGreybg.setIconSize(QtCore.QSize(18, 18))
        self.btnGreybg.setObjectName("btnGreybg")
        self.verticalLayout_3.addWidget(self.btnGreybg)
        self.btnBlackbg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBlackbg.sizePolicy().hasHeightForWidth())
        self.btnBlackbg.setSizePolicy(sizePolicy)
        self.btnBlackbg.setMinimumSize(QtCore.QSize(20, 20))
        self.btnBlackbg.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/blackbg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBlackbg.setIcon(icon9)
        self.btnBlackbg.setIconSize(QtCore.QSize(18, 18))
        self.btnBlackbg.setObjectName("btnBlackbg")
        self.verticalLayout_3.addWidget(self.btnBlackbg)
        self.hlo_enc2mot.addLayout(self.verticalLayout_3)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.hlo_enc2mot.addWidget(self.line_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlo_enc2mot.addItem(spacerItem1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.hlo_enc2mot.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 9))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(40, 9))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.txt_poscorr_a = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_poscorr_a.sizePolicy().hasHeightForWidth())
        self.txt_poscorr_a.setSizePolicy(sizePolicy)
        self.txt_poscorr_a.setMaximumSize(QtCore.QSize(70, 18))
        self.txt_poscorr_a.setReadOnly(False)
        self.txt_poscorr_a.setObjectName("txt_poscorr_a")
        self.gridLayout.addWidget(self.txt_poscorr_a, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(10, 16))
        self.label_6.setMaximumSize(QtCore.QSize(20, 22))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.txt_poscorr_b = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_poscorr_b.sizePolicy().hasHeightForWidth())
        self.txt_poscorr_b.setSizePolicy(sizePolicy)
        self.txt_poscorr_b.setMaximumSize(QtCore.QSize(70, 18))
        self.txt_poscorr_b.setReadOnly(False)
        self.txt_poscorr_b.setObjectName("txt_poscorr_b")
        self.gridLayout.addWidget(self.txt_poscorr_b, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 9))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_enccorr_a = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_enccorr_a.sizePolicy().hasHeightForWidth())
        self.txt_enccorr_a.setSizePolicy(sizePolicy)
        self.txt_enccorr_a.setMaximumSize(QtCore.QSize(70, 18))
        self.txt_enccorr_a.setReadOnly(False)
        self.txt_enccorr_a.setObjectName("txt_enccorr_a")
        self.gridLayout.addWidget(self.txt_enccorr_a, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(10, 16))
        self.label_4.setMaximumSize(QtCore.QSize(20, 22))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.txt_enccorr_b = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_enccorr_b.sizePolicy().hasHeightForWidth())
        self.txt_enccorr_b.setSizePolicy(sizePolicy)
        self.txt_enccorr_b.setMaximumSize(QtCore.QSize(70, 18))
        self.txt_enccorr_b.setReadOnly(False)
        self.txt_enccorr_b.setObjectName("txt_enccorr_b")
        self.gridLayout.addWidget(self.txt_enccorr_b, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.hlo_enc2mot.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.hlo_enc2mot)
        WindowMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSignal_Sets = QtWidgets.QMenu(self.menubar)
        self.menuSignal_Sets.setObjectName("menuSignal_Sets")
        WindowMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowMain)
        self.statusbar.setObjectName("statusbar")
        WindowMain.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(WindowMain)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(WindowMain)
        self.actionSettings.setObjectName("actionSettings")
        self.actionClosed_Loop = QtWidgets.QAction(WindowMain)
        self.actionClosed_Loop.setObjectName("actionClosed_Loop")
        self.actionCurrents = QtWidgets.QAction(WindowMain)
        self.actionCurrents.setObjectName("actionCurrents")
        self.actionTarget = QtWidgets.QAction(WindowMain)
        self.actionTarget.setObjectName("actionTarget")
        self.actionAdd_Signals = QtWidgets.QAction(WindowMain)
        self.actionAdd_Signals.setObjectName("actionAdd_Signals")
        self.actionImport_Set = QtWidgets.QAction(WindowMain)
        self.actionImport_Set.setObjectName("actionImport_Set")
        self.actionExport_Set = QtWidgets.QAction(WindowMain)
        self.actionExport_Set.setObjectName("actionExport_Set")
        self.actionSave_to_File = QtWidgets.QAction(WindowMain)
        self.actionSave_to_File.setObjectName("actionSave_to_File")
        self.actionBackup = QtWidgets.QAction(WindowMain)
        self.actionBackup.setObjectName("actionBackup")
        self.menuFile.addAction(self.actionSave_to_File)
        self.menuFile.addAction(self.actionBackup)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuSignal_Sets.addAction(self.actionClosed_Loop)
        self.menuSignal_Sets.addAction(self.actionCurrents)
        self.menuSignal_Sets.addAction(self.actionTarget)
        self.menuSignal_Sets.addAction(self.actionImport_Set)
        self.menuSignal_Sets.addAction(self.actionExport_Set)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSignal_Sets.menuAction())

        self.retranslateUi(WindowMain)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "Dummy Window Title"))
        self.labelDrivers.setText(_translate("WindowMain", "Driver"))
        self.labelSignals.setText(_translate("WindowMain", "Signal"))
        self.labelAxis.setText(_translate("WindowMain", "Y-axis:"))
        self.red_radio.setText(_translate("WindowMain", "X"))
        self.green_radio.setText(_translate("WindowMain", "X"))
        self.blue_radio.setText(_translate("WindowMain", "X"))
        self.cyan_radio.setText(_translate("WindowMain", "X"))
        self.magenta_radio.setText(_translate("WindowMain", "X"))
        self.yellow_radio.setText(_translate("WindowMain", "X"))
        self.darkred_radio.setText(_translate("WindowMain", "X"))
        self.darkgreen_radio.setText(_translate("WindowMain", "X"))
        self.darkblue_radio.setText(_translate("WindowMain", "X"))
        self.dark_cyan_radio.setText(_translate("WindowMain", "X"))
        self.dark_magenta_radio.setText(_translate("WindowMain", "X"))
        self.dark_yellow_radio.setText(_translate("WindowMain", "X"))
        self.solidline_radio.setText(_translate("WindowMain", "X"))
        self.dottedline_radio.setText(_translate("WindowMain", "X"))
        self.circlemarker_radio.setText(_translate("WindowMain", "o"))
        self.squaremarker_radio.setText(_translate("WindowMain", "s"))
        self.crossmarker_radio.setText(_translate("WindowMain", "+"))
        self.btnAdd.setText(_translate("WindowMain", "Add Signal"))
        self.labelRemove.setText(_translate("WindowMain", "Remove:"))
        self.btnRemoveSel.setText(_translate("WindowMain", "Selected"))
        self.btnRemoveAll.setText(_translate("WindowMain", "All"))
        self.btnShift.setText(_translate("WindowMain", "Shift Y-axis"))
        self.btnCLoop.setText(_translate("WindowMain", "* Closed Loop *"))
        self.btnCurrents.setText(_translate("WindowMain", "* Currents *"))
        self.btnTarget.setText(_translate("WindowMain", "* Target *"))
        self.chkEctsTurn.setText(_translate("WindowMain", "estimate"))
        self.cb_enc_sel.setItemText(0, _translate("WindowMain", "TGTENC"))
        self.cb_enc_sel.setItemText(1, _translate("WindowMain", "SHFTENC"))
        self.label.setText(_translate("WindowMain", "cnts/turn ="))
        self.btnClear.setText(_translate("WindowMain", "Clear"))
        self.btnSeeAll.setText(_translate("WindowMain", "All Data"))
        self.btnPause.setText(_translate("WindowMain", "Pause"))
        self.btnResetY.setText(_translate("WindowMain", "Reset Y"))
        self.btnResetX.setText(_translate("WindowMain", "Reset X"))
        self.btnNow.setText(_translate("WindowMain", "Now"))
        self.btnSTATUS.setText(_translate("WindowMain", "STATUS"))
        self.btnESYNC.setText(_translate("WindowMain", "ESYNC"))
        self.btnAxisOffsIncrease.setText(_translate("WindowMain", "..."))
        self.btnAxisScaleIncrease.setText(_translate("WindowMain", "..."))
        self.label_8.setText(_translate("WindowMain", "Offset"))
        self.label_9.setText(_translate("WindowMain", "Scale"))
        self.btnAxisOffsDecrease.setText(_translate("WindowMain", "..."))
        self.btnAxisScaleDecrease.setText(_translate("WindowMain", "..."))
        self.btnAxisScaleAuto.setText(_translate("WindowMain", "Auto"))
        self.cbAxisCtrlSelect.setItemText(0, _translate("WindowMain", "Y1"))
        self.cbAxisCtrlSelect.setItemText(1, _translate("WindowMain", "Y2"))
        self.cbAxisCtrlSelect.setItemText(2, _translate("WindowMain", "Y3"))
        self.cbAxisCtrlSelect.setItemText(3, _translate("WindowMain", "X"))
        self.label_10.setText(_translate("WindowMain", "Axis Ctrl"))
        self.label_3.setText(_translate("WindowMain", "Trace Corrections:"))
        self.label_5.setText(_translate("WindowMain", "POSxxx * "))
        self.txt_poscorr_a.setText(_translate("WindowMain", "1"))
        self.label_6.setText(_translate("WindowMain", "+"))
        self.txt_poscorr_b.setText(_translate("WindowMain", "0"))
        self.label_2.setText(_translate("WindowMain", "ENCxxx * "))
        self.txt_enccorr_a.setText(_translate("WindowMain", "1"))
        self.label_4.setText(_translate("WindowMain", "+"))
        self.txt_enccorr_b.setText(_translate("WindowMain", "0"))
        self.menuFile.setTitle(_translate("WindowMain", "File"))
        self.menuSignal_Sets.setTitle(_translate("WindowMain", "Signal Sets"))
        self.actionExit.setText(_translate("WindowMain", "Exit"))
        self.actionExit.setShortcut(_translate("WindowMain", "Ctrl+X"))
        self.actionSettings.setText(_translate("WindowMain", "Settings"))
        self.actionClosed_Loop.setText(_translate("WindowMain", "Closed Loop"))
        self.actionCurrents.setText(_translate("WindowMain", "Currents"))
        self.actionTarget.setText(_translate("WindowMain", "Target"))
        self.actionAdd_Signals.setText(_translate("WindowMain", "Add Signals"))
        self.actionAdd_Signals.setShortcut(_translate("WindowMain", "Ctrl+A"))
        self.actionImport_Set.setText(_translate("WindowMain", "Import Set"))
        self.actionExport_Set.setText(_translate("WindowMain", "Export Set"))
        self.actionSave_to_File.setText(_translate("WindowMain", "Save to File"))
        self.actionSave_to_File.setShortcut(_translate("WindowMain", "Ctrl+S"))
        self.actionBackup.setText(_translate("WindowMain", "Backup"))


from .square_radiobtn import Square_RadioBtn
